coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
  ignore:
    - "tests/.*"
    - "setup.py"

comment:
  layout: "header"
  require_changes: no
  behavior: default

