# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
sudo: false

services:
  - mongodb

matrix:
  include:
      - python: 3.5
      - python: 3.6
      - python: 3.7
        dist: xenial
        after_success:
          - codecov


before_install:
  - uname -a
  - free -m
  - df -h
  - pip -V
  - ulimit -a

install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov

before_script:
  - sleep 15    # fixes an issue with travis,
                # MongoDB does not accept connections immediately.
  - mongo test_bse_db --eval ';' # --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - pytest -v --cov=app/ --durations=5

notifications:
  email: false
