# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install --upgrade pip setuptools

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n bse_env python=$TRAVIS_PYTHON_VERSION pip
  - source activate bse_env
  - conda list

before_script:
  - python -V
  - pip install -e git+https://github.com/MolSSI/basis_set_exchange.git#egg=basis_set_exchange
  - pip install -e .[tests] -v
  - pip freeze

script:
  - py.test -v --cov=app/ --durations=5

notifications:
  email: false

after_success:
  - codecov